[package]
name = "raytracer"
version = "0.1.0"
authors = ["André Luis Leal Cardoso Junior <andrehjr@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.3.2"
proptest = "1.1.0"
